# Generated by Django 5.2.9 on 2025-12-23
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('persona_slug', models.SlugField(max_length=100)),
                ('total_score', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(default=dict, blank=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_sessions', to='ai_agent.call')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['persona_slug'], name='ai_agent_in_persona_abcdef_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestionState',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('index', models.IntegerField(help_text='0-based order within interview')),
                ('tech', models.CharField(max_length=64, default='general')),
                ('stage', models.CharField(max_length=32, default='basic')),
                ('question_text', models.TextField()),
                ('reference_answer', models.TextField()),
                ('key_concepts', models.JSONField(default=list, blank=True)),
                ('first_response', models.TextField(blank=True)),
                ('first_evaluation', models.CharField(max_length=16, choices=[('correct','correct'), ('partial','partial'), ('incorrect','incorrect')], blank=True)),
                ('hint_given', models.BooleanField(default=False)),
                ('second_response', models.TextField(blank=True)),
                ('final_score', models.IntegerField(null=True, blank=True)),
                ('finalized', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('derivation', models.JSONField(default=dict, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_agent.interviewsession')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('session', 'index')},
            },
        ),
    ]
