# Generated by Django 5.2.9 on 2025-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0002_interviewer_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='interviewsession',
            new_name='ai_agent_in_persona_4b417d_idx',
            old_name='ai_agent_in_persona_abcdef_idx',
        ),
        migrations.AlterField(
            model_name='interviewquestionstate',
            name='derivation',
            field=models.JSONField(blank=True, default=dict, help_text='Why this score was assigned'),
        ),
    ]
